### PR TITLE
styled tables and cleaned up whitespace

### PR DESCRIPTION
**Pull request by egladman**

### CODE REVIEW

**Comment by J3RN** [comment]
HOLY THIS IS BEAUTIFUL

**Comment by J3RN** [comment]
@egladman Would you like to rebase against master yourself, or assume that I will do a non-shitty job?

**Comment by egladman** [comment]
@J3RN i'll take a look at it

**Comment by J3RN** [comment]
Oh, also - I consider `git merge master` and acceptable solution (assuming your `master` is up to date). I get so caught up in how things are done at CMM.

**Pull request closed without merging**
